-- liquibase formatted changelog
-- changeset ppickerill:create-actor-table
CREATE TABLE public.actor (
	actor_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	first_name varchar(45) NOT NULL,
	last_name varchar(45) NOT NULL,
	last_update timestamp NOT NULL DEFAULT now(),
	CONSTRAINT actor_pkey PRIMARY KEY (actor_id)
);

-- changeset ppickerill:add-phone-to-employees
-- ALTER TABLE integration.EMPLOYEES ADD PHONE_NUMBER varchar(15) NOT NULL DEFAULT "555-555-5555";
